### ISSUE TITLE
alkad-eac

### ISSUE THREAD

**Issue by Mayorov79997** [spacecollapse/alkad-eac-bypass#1]
Greetings, update 2556 has been released, an update is needed

**Comment by spacecollapse** [comment]
bypass is already updated, but cheat not

**Comment by spacecollapse** [comment]
or u have any updated cheat?

**Comment by Mayorov79997** [comment]
![2024-09-07_11-09-11](https://github.com/user-attachments/assets/92d1bdb8-f60f-4bcd-bc38-473333074820)
![2024-09-07_11-09-05](https://github.com/user-attachments/assets/22dbed1c-374a-4e3b-aef3-e713cbfb6c04)

**Comment by Mayorov79997** [comment]
Steam is open, but this error pops up

**Comment by spacecollapse** [comment]
I updated the bypass but haven't posted it yet because what's the point of posting it now if there's no updated cheat

**Comment by Mayorov79997** [comment]
That's also true

**Comment by spacecollapse** [comment]
upload new version
